<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2EUUN60H" failures="1" tests="5" name="Submit Order Test" time="37.919" errors="0" timestamp="2023-09-15T10:49:42 IST">
  <testcase classname="StandaloneTest" name="LoginErrorValidation" time="0.769"/>
  <testcase classname="StandaloneTest" name="submitOrder" time="8.115"/>
  <testcase classname="StandaloneTest" name="submitOrder" time="8.134"/>
  <testcase classname="StandaloneTest" name="OrderHistoryTest" time="0.866">
    <skipped/>
  </testcase> <!-- OrderHistoryTest -->
  <testcase classname="StandaloneTest" name="OrderHistoryTest" time="0.912">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at StandaloneTest.OrderHistoryTest(StandaloneTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- OrderHistoryTest -->
</testsuite> <!-- Submit Order Test -->
